### ISSUE TITLE
Problem with bloomfilter

### ISSUE THREAD

**Issue by evolgenomology** [bcgsc/LINKS#19]
Hello!

I have the following error message when excecuting LINKS
```
Can't load '/data2/bioProgs/LINKS/releases/links_v1.8.6/./lib/bloomfilter/swig/BloomFilter.so' for module BloomFilter: /data2/bioProgs/LINKS/releases/links_v1.8.6/./lib/bloomfilter/swig/BloomFilter.so: undefined symbol: PL_stack_sp at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 187.
 at /data2/bioProgs/LINKS/releases/links_v1.8.6/./lib/bloomfilter/swig/BloomFilter.pm line 11.
Compilation failed in require at ./LINKS line 26.
BEGIN failed--compilation aborted at ./LINKS line 26.
```  
The thing is, the compilation of the bloomfilter went without a problem. I can run the test.pl script within the swig subdirectory and it just works, no error messages whatsoever.
Would be great to get some help with this. 
Thanks

Philipp

**Comment by warrenlr** [comment]
I assume you're using the same version of PERL as that used to build the module (CORE) and used by the test script.  Could you also try ./tools/testBloom.pl  and ./writeBloom.pl  ?
@JustinChu : thoughts?

**Comment by evolgenomology** [comment]
I am pretty sure I do (BTW. I forgot to say, this is on an Ubuntu 16.04).

```
./tools/testBloom.pl
Can't load '/data2/bioProgs/LINKS/releases/links_v1.8.6/tools/../lib/bloomfilter/swig/BloomFilter.so' for module BloomFilter: /data2/bioProgs/LINKS/releases/links_v1.8.6/tools/../lib/bloomfilter/swig/BloomFilter.so: undefined symbol: PL_stack_sp at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 187.
 at /data2/bioProgs/LINKS/releases/links_v1.8.6/tools/../lib/bloomfilter/swig/BloomFilter.pm line 11.
Compilation failed in require at ./tools/testBloom.pl line 30.
BEGIN failed--compilation aborted at ./tools/testBloom.pl line 30.
```

```
./tools/writeBloom.pl
zsh: ./tools/writeBloom.pl: bad interpreter: /home/martink/perl/5.10.0/bin/perl: no such file or directory
```

So this one has a hard link to a wrong perl for sure.
Meanwhile, if go into the links_v1.8.6/bloomfilter/swig/ folder and excute the two _rolling scripts, they don't give an error.

**Comment by evolgenomology** [comment]
I got this setup:
```
  %ENV:
    PERL5LIB="/data2/bioProgs/JAMg/PerlLib:/home/philipp/bioProgs/JAMg/3rd_party/transdecoder/PerlLib"
  @INC:
    /data2/bioProgs/JAMg/PerlLib
    /home/philipp/bioProgs/JAMg/3rd_party/transdecoder/PerlLib
    /etc/perl
    /usr/local/lib/x86_64-linux-gnu/perl/5.22.1
    /usr/local/share/perl/5.22.1
    /usr/lib/x86_64-linux-gnu/perl5/5.22
    /usr/share/perl5
    /usr/lib/x86_64-linux-gnu/perl/5.22
    /usr/share/perl/5.22
    /usr/local/lib/site_perl
    /usr/lib/x86_64-linux-gnu/perl-base
    .
```
So guess that is fine with what I build the bloomfilter against.

**Comment by warrenlr** [comment]
I see. Yes, I may have forgotten to replace the shebang to #!/usr/bin/env perl
after testing.  I'll make the changes, if applicable. Otherwise, you just need to preceed the command by your version of PERL or change the 1st line of LINKS/

**Comment by evolgenomology** [comment]
That doesn't really help though. I had already tried to set the shebang in LINKS to my perl, but that leads to the same error. Same thing if I execute with `/usr/bin/perl5.22.1 ./LINKS`.

**Comment by warrenlr** [comment]
I take it back, LINKS is fine.  

the /usr/bin/perl version is probably different that the one in your environment.  Since the former works (that's the one in the shebang of ./swig/test.pl), you could launch LINKS this way:

/usr/bin/perl LINKS -f blah

Let me know

**Comment by evolgenomology** [comment]
```
/usr/bin/perl ./LINKS -f /data1/final_N90_3_JAMg/all_incorporated_final.fna.500bp.underscore.fna -s /GenomeData_telfordNAS/Xenoturbella/Birmingham_NanoP/all_ONT.fof -b /data1/final_N90_3_JAMg/all_incorporated_final.fna.500bp.underscore.LINKS1
Can't load '/data2/bioProgs/LINKS/releases/links_v1.8.6/./lib/bloomfilter/swig/BloomFilter.so' for module BloomFilter: /data2/bioProgs/LINKS/releases/links_v1.8.6/./lib/bloomfilter/swig/BloomFilter.so: undefined symbol: PL_stack_sp at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 187.
 at /data2/bioProgs/LINKS/releases/links_v1.8.6/./lib/bloomfilter/swig/BloomFilter.pm line 11.
Compilation failed in require at ./LINKS line 26.
BEGIN failed--compilation aborted at ./LINKS line 26.
```

**Comment by warrenlr** [comment]
what if you copy LINKS to ./links_v1.8.6/lib/bloomfilter/swig

edit LINKS and change:
1st line: #!/usr/bin/perl

comment out (place #) before : use lib "$FindBin::Bin/./lib/bloomfilter/swig";

**Comment by evolgenomology** [comment]
OK, here is something. I am using tmux. In the pane I had installed/build everying I could do:
```
/data2/bioProgs/LINKS/releases/links_v1.8.6/bloomfilter/swig/ ./test.pl
de novo bf tests done
Storing filter. Filter is 125000000 bytes.
premade bf tests done
Filter Info: Pop - 20, numHash - 5, kmerSize - 20, size - 1000000000
0 TAGAA found
1 AGAAT found
2 GAATC found
3 AATCA found
4 ATCAC found
5 TCACC found
6 CACCC found
7 ACCCA found
8 CCCAA found
9 CCAAA found
10 CAAAG found
11 AAAGA found
Done!
```

But LINKS failed as described above. However, now I went to a new pane, i.e. fresh environment and 
```
/data2/bioProgs/LINKS/releases/links_v1.8.6/lib/bloomfilter/swig/ ./test.pl
Can't load './BloomFilter.so' for module BloomFilter: ./BloomFilter.so: undefined symbol: PL_stack_sp at /usr/lib/x86_64-linux-gnu/perl/5.22/DynaLoader.pm line 187.
 at BloomFilter.pm line 11.
Compilation failed in require at ./test.pl line 3.
BEGIN failed--compilation aborted at ./test.pl line 3.
```  

So it must be something with the PATH of the swig folder not being found for whatever reason.

**Comment by evolgenomology** [comment]
OK! Solved.
I re-did the build of the BloomFilter with `sudo` and now LINKS fires up. Maybe the BloomFilter.so has to be owned by root?

**Comment by warrenlr** [comment]
I'm running out of ideas here.  I find it strange that the test.pl in the swig directory works but no other scripts. Suggests that the module compiled ok.  It is worth adapting LINKS to be as similar to test.pl in how you run it (it's the easiest thing to test/do).

I found this old issue though: https://github.com/bcgsc/LINKS/issues/5
Maybe it can offer some clues?

fyi, I get the same error as you when the PERL version I invoke is different from the one used to build the BloomFilter.pm module. Some systems are capricious when it comes to PERL versions..

**Comment by warrenlr** [comment]
ok, just seeing your comment 👍 👍 
hmm strange though.. but as long as it works!! :)

**Comment by evolgenomology** [comment]
Ja, thanks man! Running on my genome now. Excited...
