### ISSUE TITLE
packaging in Anaconda - request/question

### ISSUE THREAD

**Issue by devonorourke** [bcgsc/LINKS#22]
Given that an older LINKS version had been produced as an Anaconda distribution ([see here](https://anaconda.org/bioconda/links)), I was wondering if it would be possible to package the more recent versions in the same manner?
If so, would the dependency of installing the PERL modules persist, or automatically be generated? It's been my experience (as a total computer novice) that the dependency issue has required system administrator privileges and has made troubleshooting more time consuming.
Thanks for your consideration and information

**Comment by warrenlr** [comment]
this was done by third party;  I have opened an issue https://github.com/bioconda/bioconda-recipes/issues/9758

to speed things up you may want to submit a pull request that updates the package recipe with the binary I mentioned in the above bioconda ticket. thanks, Rene
