### ISSUE TITLE
LINKS run terminated without any error message in the .log file, not getting output files

### ISSUE THREAD

**Issue by drashutosh** [bcgsc/LINKS#23]
Hi 
I am running LINKS to scaffolding a draft genome assembly using the following command
```
LINKS -f /home/ashutosh/assembly/assembly_1kb.fa -s /home/ashutosh/assembly/fof -b 1kb_raw
```
However, After producing the 1kb_raw.bloom file, no more output files are generating and the log file is showing the following status after the LINKS run terminated

```
### Running: /home/ashutosh/LINKS/releases/links_v1.8.6/LINKS [v1.8.6]
-f /home/ashutosh/assembly/assembly_1kb.fa
-s /home/ashutosh/assembly/fof
-m
-d 4000
-k 15
-e 0.1
-l 5
-a 0.3
-t 2
-o 0
-z 500
-b 1kb_raw
-r
-p 0.001
-x 0

----------------- Verifying files -----------------

Checking /home/ashutosh/asmset_longread/assembly.chopped.filt.fastq...ok
Checking sequence target file /home/ashutosh/assembly/assembly_1kb.fa...ok

=>Reading contig/sequence assembly file : Wed Jul  4 11:42:36 AEST 2018
Building a Bloom filter using 15-mers derived from sequences in -f /home/ashutosh/assembly/assembly_1kb.fa...
*****
Bloom filter specs
elements=908707947
FPR=0.001
size (bits)=13065028096
hash functions=9
*****
Contigs (>= 500 bp) processed k=15:
2866

=>Writing Bloom filter to disk (1kb_raw.bloom) : Wed Jul  4 12:05:52 AEST 2018

```
Could you please advise me regarding this issues

Thanks in advanced

**Comment by warrenlr** [comment]
hmm puzzling. Are you running LINKS on A) its own (ie. scaffolding with long reads?) or B) pipelined with ARC/KS?

If
A) :

i) Did you try re-running, this time run with -r 1kb_raw.bloom

ii) Alternatively, try using the ./tools/writeBloom.pl utility to first make the Bloom filter and feed it in LINKS.

iii) Also, you could turn off the Bloom filter utility with -x 1 and see if you get stuck at the same place

iv) If you ran LINKS in this directory before, with the SAME basename, LINKS will override .scaffolds and .scaffolds.fa when different -l and -a params are specified. The run will be very fast because the sequence pairing info from .tigpair_checkpoint.tsv will be used instead of remapping all kmers.


B):
i) is .tigpair_checkpoint.tsv empty ?

**Comment by drashutosh** [comment]
Hi Rene
Thank you very much
Yes, I am running LINKS on its own i.e. scaffolding with long reads
I tried with creating  the Bloom filter by /tools/writeBloom.pl and feed it in LINKS.
This time I use an iterative run with the following command 

```
LINKS -f /home/ashutosh/assembly/assembly_1kb.fa \
  -s  /home/ashutosh/assembly/fof  \
  -b 1kb_raw \
  -d 1000,2500,5000,7500,10000,12500,15000,30000 \
  -t 10,5,5,4,4,3,3,2 \
  -k 15 \
  -r 1kb_raw.bloom \
  -p 0.0001
```
and I got stuck at the same point only got 1kb_raw.bloom  and 1kb_raw.log file, and the log file end with the following texts-
```
Building a Bloom filter using 15-mers derived from sequences in -f /home/ashutosh/assembly/assembly_1kb.fa...
*****
Bloom filter specs
elements=908707947
FPR=0.001
size (bits)=13065028096
hash functions=9
*****
Contigs (>= 500 bp) processed k=15:
2866
=>Writing Bloom filter to disk (1kb_raw.bloom) : Thu Jul  5 12:55:14 AEST 2018
```

Now I am running a new run with turn off the Bloom filter utility with -x 1, I will keep posting, if something come-out from this run

**Comment by warrenlr** [comment]
if you provided the bloom filter, it should not write a new one (your log file).
I have no idea what the problem is and why there's unexpected termination. I wonder if the BF was compiled properly and whether you have enough RAM on your machine.

**Comment by drashutosh** [comment]
hi @warrenlr 
Yes, even after providing the .bloom file I aam getting the same problem 
```
Running: /home/ashutosh/LINKS/releases/links_v1.8.6/LINKS [v1.8.6]
-f /home/ashutosh/assembly/assembly_1kb.fa
-s /home/ashutosh/assembly/fof
-m
-d 1000,2500,5000,7500,10000,12500,15000,30000
-k 15
-e 0.1
-l 5
-a 0.3
-t 10,5,5,4,4,3,3,2
-o 0
-z 500
-b 1kb_raw
-r
-p 0.001
-x 0
----------------- Verifying files -----------------
Checking /home/ashutosh/asmset_longread/assembly.chopped.filt.fastq...ok
Checking sequence target file /home/ashutosh/assembly/assembly_1kb.fa...ok
=>Reading contig/sequence assembly file : Wed Jul 11 09:53:26 AEST 2018
Building a Bloom filter using 15-mers derived from sequences in -f /home/ashutosh/assembly/assembly_1kb.fa...
*****
Bloom filter specs
elements=908707947
FPR=0.001
size (bits)=13065028096
hash functions=9
*****
Contigs (>= 500 bp) processed k=15:
2866
=>Writing Bloom filter to disk (1kb_raw.bloom) : Fri Jul  6 10:35:15 AEST 2018
```
It seems like bloom filter hasn't taken by the LINKS run
Do you have any idea on that
Thanks in advanced
