### ISSUE TITLE
Output analysis confusion!

### ISSUE THREAD

**Issue by veronneaupy** [bcgsc/LINKS#25]
Hi, 
I just ran links_v1.8.6 on my CANU genome assembly and I'm not sure how to interpret the results.
When I run QUAST on my output, it is exactly the same as the input...

Here is the log:
 _Running: ./LINKS [v1.8.6]
-f long_long2.fasta
-s matepair.fof
-m 1
-d 1000
-k 15
-e 0.5
-l 5
-a 0.3
-t 20
-o 0
-z 500
-b mpet1k_v2
-r 
-p 0.001
-x 0

----------------- Verifying files -----------------

Checking mpet1k_1.fa_paired.fa...ok
Checking sequence target file long_long2.fasta...ok

=>Reading contig/sequence assembly file : jeudi 12 juillet 2018, 11:30:18 (UTC-0400)
Building a Bloom filter using 15-mers derived from sequences in -f long_long2.fasta...
*****
Bloom filter specs
elements=253506447
FPR=0.001
size (bits)=3644811200
hash functions=9
*****
Contigs (>= 500 bp) processed k=15:
2402

=>Writing Bloom filter to disk (mpet1k_v2.bloom) : jeudi 12 juillet 2018, 11:33:10 (UTC-0400)

=>Reading long reads, building hash table : jeudi 12 juillet 2018, 11:33:10 (UTC-0400)
Reads processed k=15, dist=1000, offset=0 nt, sliding step=20 nt:

Reads processed from file 1/1, mpet1k_1.fa_paired.fa:
133240440
Extracted 220116677 15-mer pairs at -d 1000, from all 133240440 sequences provided in matepair.fof
Extracted 220116677 15-mer pairs overall. This is the set that will be used for scaffolding

=>Reading sequence contigs (to scaffold), tracking k-mer positions : jeudi 12 juillet 2018, 12:27:56 (UTC-0400)

Contigs (>= 500 bp) processed k=15:
2402
=>Scaffolding initiated : jeudi 12 juillet 2018, 12:45:36 (UTC-0400)

===========PAIRED K-MER STATS===========
Total number of pairs extracted from -s matepair.fof: 220116677
At least one sequence/pair missing from contigs: 0
Ambiguous kmer pairs (both kmers are ambiguous): 20104140
Assembled pairs: 1515121 (3030242 sequences)
	Satisfied in distance/logic within contigs (i.e. -> <-, distance on target: 4294
	Unsatisfied in distance within contigs (i.e. distance out-of-bounds): 509692
	Unsatisfied pairing logic within contigs (i.e. illogical pairing ->->, <-<- or <-->): 587143
	---
	Satisfied in distance/logic within a given contig pair (pre-scaffold): 47
	Unsatisfied in distance within a given contig pair (i.e. calculated distances out-of-bounds): 413945
	---
Total satisfied: 4341	unsatisfied: 1510780

Breakdown by distances (-d):
--------k-mers separated by 1000 bp (outer distance)--------
MIN:500 MAX:1500 as defined by 1000 * 0.5
At least one sequence/pair missing: 
Assembled pairs: 1515121
	Satisfied in distance/logic within contigs (i.e. -> <-, distance on target: 4294
	Unsatisfied in distance within contigs (i.e. distance out-of-bounds): 509692
	Unsatisfied pairing logic within contigs (i.e. illogical pairing ->->, <-<- or <-->): 587143
	---
	Satisfied in distance/logic within a given contig pair (pre-scaffold): 47
	Unsatisfied in distance within a given contig pair (i.e. calculated distances out-of-bounds): 413945
============================================

We are in the last steps of our genome assembly draft, so please help me understanding the output

thanks a lot,

PY

**Comment by warrenlr** [comment]
you should definitely try larger values of -d (esp. since you have a long read assembly, I doubt you'd get any merges at such low kmer pair intervals).  My suggestion is to run LINKS iteratively (looks at other issues/demo for guidance on how to set, with increasing -d, decrease -t.

**Comment by veronneaupy** [comment]
Hi,

Thanks for the reply. I thought the -d option was to declare the distance between matepair (in the .fof).
I just tried :

_./LINKS -f long_long2.fasta -s matepair.fof -m 1 -b mpet5k_16juil -d 5000,10000 -t 10,15 -k 21 -l 5 -a 0.3 -o 0_

I didn't change anything compare to my input. Can I try something else? If not I'll move on to another program.

thanks,
PY

**Comment by warrenlr** [comment]
that's strange, what coverage do you have from MP?
I think abyss-scaffold should work well on your MP data
