### ISSUE TITLE
No links using ONT 

### ISSUE THREAD

**Issue by bbista** [bcgsc/LINKS#37]
I am trying to scaffold a relatively fragmented illumina assembly using ONT reads. I have done iterations with different parameter values yet I find no links in the contigs.
./LINKS -f $genome -s $nano -b Nano -d 500,1000,2000,3000,4000,5000,6000,7000  -e $e 
 The ONT reads are definitely less than 10X coverage
What do you think might be causing this?  

===========PAIRED K-MER STATS===========
Total number of pairs extracted from -s /home/nano.txt: 38852317
At least one sequence/pair missing from contigs: 0
Ambiguous kmer pairs (both kmers are ambiguous): 38828431
Assembled pairs: 0 (0 sequences)
	Satisfied in distance/logic within contigs (i.e. -> <-, distance on target: 0
	Unsatisfied in distance within contigs (i.e. distance out-of-bounds): 0
	Unsatisfied pairing logic within contigs (i.e. illogical pairing ->->, <-<- or <-->): 0
	---
	Satisfied in distance/logic within a given contig pair (pre-scaffold): 0
	Unsatisfied in distance within a given contig pair (i.e. calculated distances out-of-bounds): 0
	---
Total satisfied: 0	unsatisfied: 0

**Comment by lcoombe** [comment]
Hi @bbista,
The first thing I would try is increasing the k-value to attempt to reduce the ambiguity -- how large is the genome that you are trying to scaffold?
Have you tested your LINKS installation on one of the provided tests?

**Comment by bbista** [comment]
Hello,
The genome is around 2.5 Gbs. 
I have run the runme_EcoliK12single.sh test only.

**Comment by bbista** [comment]
I looked at the log files for runme_EcoliK12single.sh.  The following seems unusual.


===========PAIRED K-MER STATS===========
Total number of pairs extracted from -s K12_F2D.fof: 3919530
At least one sequence/pair missing from contigs: 0
Ambiguous kmer pairs (both kmers are ambiguous): 3919530
Assembled pairs: 0 (0 sequences)
	Satisfied in distance/logic within contigs (i.e. -> <-, distance on target: 0
	Unsatisfied in distance within contigs (i.e. distance out-of-bounds): 0
	Unsatisfied pairing logic within contigs (i.e. illogical pairing ->->, <-<- or <-->): 0
	---
	Satisfied in distance/logic within a given contig pair (pre-scaffold): 0
	Unsatisfied in distance within a given contig pair (i.e. calculated distances out-of-bounds): 0
	---
Total satisfied: 0	unsatisfied: 0

**Comment by lcoombe** [comment]
Hi @bbista,

What is the name of log file that is from? Just since that tests runs a number of LINKS runs and I want to be sure I'm comparing your results to my local test.

If you are seeing no scaffolding in the test run, though, that does seem to indicate an issue with your installation. Were you able to build and test the Bloom filter OK?

**Comment by bbista** [comment]
The name of the loag file is ecoliK12-ONT_linksSingleIterationTIG.log

**Comment by lcoombe** [comment]
Yes, you should be seeing some satisfied kmer pairs in that test.
My first guess would be an issue with compiling the Bloom filter. Take a look at running the tests for the BF to see if they pass OK on your system.

**Comment by bbista** [comment]
Hello, 
I was a problem with compliling the bloom filter. It seems to work now that i reinstalled everything.
The log file ecoliK12-ONT_linksSingleIterationTIG.log shows this now.
===========PAIRED K-MER STATS===========
Total number of pairs extracted from -s K12_F2D.fof: 81690
At least one sequence/pair missing from contigs: 0
Ambiguous kmer pairs (both kmers are ambiguous): 13327
Assembled pairs: 68363 (136726 sequences)
	Satisfied in distance/logic within contigs (i.e. -> <-, distance on target: 54722
	Unsatisfied in distance within contigs (i.e. distance out-of-bounds): 579
	Unsatisfied pairing logic within contigs (i.e. illogical pairing ->->, <-<- or <-->): 303
	---
	Satisfied in distance/logic within a given contig pair (pre-scaffold): 667
	Unsatisfied in distance within a given contig pair (i.e. calculated distances out-of-bounds): 12092
	---
Total satisfied: 55389	unsatisfied: 12974

Thank you.

**Comment by lcoombe** [comment]
@bbista - Great, I'm glad you got everything working OK!
