### ISSUE TITLE
Illumina contig scaffolding with PacBio reads

### ISSUE THREAD

**Issue by hidvegin** [bcgsc/LINKS#39]
I have got a fastq file with draft genome contigs from Illumina paired-end reads and 10x Genomics reads by ABySS. I would like to scaffold this contigs with PacBio reads (about 30x coverage) by LINKS. Should I make corrected and trimmed PacBio reads for LINKS or not? I did not find any information about this in the manual. What is the recommended computing resource ( cpu core, memory and free space size) for 4Gb de novo plant genome?

**Comment by lcoombe** [comment]
Hi @hidvegin,

If you have an established pipeline for correcting/trimming PacBio reads, then I think that is worth doing. The more correct your reads are, the better.

LINKS runs single-threaded, and the RAM usage will vary quite widely depending on the parameters that you set and your input data. I would expect the memory usage to range anywhere from ~200GB - 900GB depending on these settings. If you find that you are running out of memory on a LINKS run, you can increase the `-t` parameter (step of sliding window) to lower the memory usage.

Hope that helps!
Lauren

**Comment by hidvegin** [comment]
Thnk you for your answer. Can we run LINKS on a HPC cluster? Is there any solution for that run LINKS on multiple threads? How many CPU hours takes the LINKS run on single thread?

**Comment by lcoombe** [comment]
Hi @hidvegin,

You can run LINKS on a computing cluster, and how well that works will depend on the specifications of those machines. 
LINKS runs in a single thread, so you cannot use multiple threads at this time. 
How long a run will take varies widely with the parameters used and the input data. Recent tests runs I've done with human data took ~1-2 days.

**Comment by hidvegin** [comment]
Thank you for your answer again. It is clear now. I close this issue and I will start the LINKS run on the cluster. If I will some questions about LINKS I will contact with you again, thanks.
