### ISSUE TITLE
Very small contig parameters

### ISSUE THREAD

**Issue by rajewski** [bcgsc/LINKS#43]
I'm looking for some advice on how to reduce the number of small contigs.

I'm running LINKS on an ABySS assembly that is highly fragmented (3.8 million contigs, 1.7kb N50, and ~2Gbp genome size). I have corrected ONT reads at roughly 7x coverage. Over half of my contigs are <250bp. So far I've set k=15, l=4 and started with d=1000 and t=10. This reduced the contig number by 100,000 but that's a drop in the bucket for 3.8 million. Theoretically though with these parameters, a 100bp contig has a small chance of being scaffolded. Which parameters are best to tune first in order to scaffold up small contigs?

Given that I have corrected long reads, would it be safer to reduce -l or would starting with a smaller -d be better?

**Comment by warrenlr** [comment]
What is the length of your short read data? Did you run ABySS at different k values?  If not, I highly recommend that you do -- at least to the unitig stage -- and plot k  vs N50 to determine which assembly to push forward.

As for LINKS, starting with smaller d may help capture the short guys (I never tried <1000, but it is definitely worth giving it a shot on your very fragmented assembly). Perhaps -d 250, 500, 750, 1000, ...

I find your k quite low for corrected ONT reads derived from a 2Gbp genome.  Increasing it (17, 19) would increase confidence in the joins and perhaps even boost the number of linkages (there *might* be many conflicts at k15 that prevent LINKS from merging contigs.

Parameter -l is the #supporting kmer pairs; we have used as low as 2, but of course, the lower the higher the chance of spurious scaffolds..something to keep in mind

Another parameter to adjust is -a (the link ratio).  It is set at 0.3 by default.  When LINKS finds a fork in the scaffold graph, it compares kmer pair support between the second-most supported and top supported path, and scaffolds only if its 3 to 10 (3/10 = 0.3) or less.  You could sweep through this parameter and the -l parameter WITHOUT having to run LINKS from the beginning; All you need to do is to give it the same command in the same directory, but changing -a and -l (the output will be re-written if you use the same filename -b, so you will want to make a copy to track the final output).  

Good luck!
Rene

**Comment by rajewski** [comment]
The short read data is 2x150bp, so I suspect that most of my small contigs are actually between 150 and 249bp. Also for the ABySS assembly I tried it with 16 different kmer sizes ranging from 33 to 127 and picked the highest N50 as you suggest.

I did lower the threshold for -z to capture these smaller contigs. I'll try increasing the k and running it with a few iterations at low -d as you suggest.

So you don't think that altering the -t parameter will have as significant of an effect as the others? I guess if I can change -l without rerunning LINKS, then -l would be quicker to play with than -t.

**Comment by warrenlr** [comment]
yes, altering the t parameter (lowering it), provided you have sufficient RAM, would give you more kmer pairs to work with. this will be important as you increase k

**Comment by rajewski** [comment]
I just finished the first iteration with -d 250, -t 6, -k 19 and it scaffolded 100,000 contigs away and nearly doubled my N50. LINKS found 800 million kmer pairs to work with, so it took nearly 700Gb of RAM and 18 hours, but that's not a terrible problem on our HPC.

I haven't played with -a  or -l yet, but the assembly_correspondence.tsv file shows that most of the link-ratios are below 0.3 so I don't suspect that lowering -a would improve much.

I very much appreciate the timely advice.

**Comment by warrenlr** [comment]
this is great feedback, thanks for sharing!

Rene
