### ISSUE TITLE
Identifying the long read(s) that contig pair scaffolding is based upon 

### ISSUE THREAD

**Issue by ckeeling** [bcgsc/LINKS#44]
Is there a way to identify which long read(s) in the reads input provide the information for two contigs in the assembly input to be scaffolded?  I have a situation where two very long contigs are being scaffolded where the orthologous long contigs in the long read input file are separate contigs.  Maybe another long read is providing the scaffolding info, but which one?

**Comment by warrenlr** [comment]
not in the current implementation.  That would be a lot of extra info to store in memory. A fast file lookup might be an option in the future. If you know the identity of the two contigs, you could run rails on the whole assembly/read set and parse the minimap2 bam file for those two contigs, hoping that a read alignment-based scaffolding recapitulates the kmer-based method of links for this specific merge.

**Comment by ckeeling** [comment]
OK, thanks
