### ISSUE TITLE
BloomFilter_wrap.cxx:763:20: fatal error: EXTERN.h: No such file or directory

### ISSUE THREAD

**Issue by bioramg** [bcgsc/LINKS#45]
Hi,
After a long struggle, I successfully compiled Perl Module. 
When I try to assemble using the following command, I am getting the following error. 

 ./../bin/bin/LINKS-master/bin/LINKS -f scaffoldsK77_full_ONT\ extraction.fasta -s 201907_ONT_PSJ.fastq.gz -d 1000,2500,5000,7500,10000,12500,15000,30000 -t 10,5,5,4,4,3,3,2 -b ./LINK_ONT_23032020

Can't locate BloomFilter.pm in @INC (you may need to install the BloomFilter module) (@INC contains: /home/pmslab/Desktop/Raman/bin/bin/LINKS-master/bin/./lib/bloomfilter/swig /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./../bin/bin/LINKS-master/bin/LINKS line 26.

BEGIN failed--compilation aborted at ./../bin/bin/LINKS-master/bin/LINKS line 26.

Please help to sort out this issue. Thank you.

**Comment by warrenlr** [comment]
hmm only thing I can think of, is to make sure the newly built Bloom filter is in your PATH.

other option is to change the LINKS code:

use lib /path-to-lib/

@lcoombe any other suggestions?

**Comment by lcoombe** [comment]
Hi @bioramg,
Yes, it looks like the script cannot find the compiled Bloom Filter module. This line in the script describes where LINKS is expecting to find the BloomFilter:
`use lib "$FindBin::Bin/./lib/bloomfilter/swig";`
As Rene mentioned, does that correspond to the location of the compiled module on your system? 
Have you tried running the Bloom filter test scripts located in that `swig` directory where you compiled the BloomFilter?

As a side note, LINKS is available in both homebrew and bioconda, which makes the installation much easier.

**Comment by bioramg** [comment]
Hi,
Thank you for your response.
I have done at swig.
I am getting an error
I tried with ./tools/testBloom.pl and ./writeBloom.pl commands. Both are working fine.

When I try to assemble using the following command, I am getting the following error.

./../bin/bin/LINKS-master/bin/LINKS -f scaffoldsK77_full_ONT\ extraction.fasta -s 201907_ONT_PSJ.fastq.gz -d 1000,2500,5000,7500,10000,12500,15000,30000 -t 10,5,5,4,4,3,3,2 -b ./LINK_ONT_23032020

Can't locate BloomFilter.pm in @inc (you may need to install the BloomFilter module) (@inc contains: /home/pmslab/Desktop/Raman/bin/bin/LINKS-master/bin/./lib/bloomfilter/swig /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at ./../bin/bin/LINKS-master/bin/LINKS line 26.

BEGIN failed--compilation aborted at ./../bin/bin/LINKS-master/bin/LINKS line 26.

**Comment by bioramg** [comment]
> hmm only thing I can think of, is to make sure the newly built Bloom filter is in your PATH.
> 
> other option is to change the LINKS code:
> 
> use lib /path-to-lib/
> 
> @lcoombe any other suggestions?

How to change link code? I'm a beginner in Bioinformatics.

**Comment by bioramg** [comment]
> Hi @bioramg,
> Yes, it looks like the script cannot find the compiled Bloom Filter module. This line in the script describes where LINKS is expecting to find the BloomFilter:
> `use lib "$FindBin::Bin/./lib/bloomfilter/swig";`
> As Rene mentioned, does that correspond to the location of the compiled module on your system?
> Have you tried running the Bloom filter test scripts located in that `swig` directory where you compiled the BloomFilter?
> 
> As a side note, LINKS is available in both homebrew and bioconda, which makes the installation much easier.

When I use that command, it says command not found

**Comment by lcoombe** [comment]
If the test commands worked OK, then the most likely reason for the failure is that you aren't pointing to the correct location of the compiled Bloom filter.

This line in the LINKS script indicates where it expects the compiled Bloom filter to be relative to the script:
```
use lib "$FindBin::Bin/./lib/bloomfilter/swig";
```
Is that the correct path on your system? If not, you can edit that line to reflect the location of the compiled module.

**Comment by warrenlr** [comment]
the simplest thing to do for you is:

1) move ./../bin/bin/LINKS-master/lib

mv ./../bin/bin/LINKS-master/lib. ./../bin/bin/LINKS-master/lib-old

2) move your rebuild BloomFilter modules to ./../bin/bin/LINKS-master/lib

mv WHERE-YOU-BUILT ./../bin/bin/LINKS-master/lib


This way you don't have to edit LINKS

**Comment by bioramg** [comment]
> the simplest thing to do for you is:
> 
> 1. move ./../bin/bin/LINKS-master/lib
> 
> mv ./../bin/bin/LINKS-master/lib. ./../bin/bin/LINKS-master/lib-old
> 
> 1. move your rebuilt BloomFilter modules to ./../bin/bin/LINKS-master/lib
> 
> mv WHERE-YOU-BUILT ./../bin/bin/LINKS-master/lib
> 
> This way you don't have to edit LINKS

Sorry to ask you again. Where should I execute these commands? I mean path?

**Comment by bioramg** [comment]
I have executed all these commands at ./LINKS-master/releases/link_v1.8.7/lib/bloomfilter/swig/

swig -Wall -c++ -perl5 BloomFilter.i
g++ -c BloomFilter_wrap.cxx -I/usr/lib/x86_64-linux.gnu/perl/5.22.1/CORE -fPIC -Dbool=char -O3
g++ -Wall -shared BloomFilter_wrap.o -o BloomFilter.so -O3

**Comment by bioramg** [comment]
Hi,
Sorry for the inconvenience. There is no two lib folder in LINKS-master/
Only one lib is folder is located at ./LINKS-master/releases/link_v1.8.7/lib
