### ISSUE TITLE
System is not responding and Pairing issues

### ISSUE THREAD

**Issue by bioramg** [bcgsc/LINKS#48]
Hi,
I am trying to assemble a hybrid assembly (Illumina and Nanopore) contigs with LINKS. 

First, I generated .fof file for ONT sequences:
gunzip -c ONT.fastq.gz | perl -ne '$ct++;if($ct>4){$ct=1;}print if($ct<3);' > ONT.fa
echo ONT.fa_paired.fa > ONT.fof
Is it correct for Nanopore sequencing raw reads?

Second, I used the following commands for scaffold assembly:
bin$LINKS -f contigs.fa -s ONT.fof -d 1000,2500,5000,5000,7500,10000,12500,15000,30000 -t 10,5,5,4,4,3,3,2 -b ONT_scaffold

The contig file is containing 101 contigs. 

After one day, the system is not responding and not getting any results. In the output files, I can able to get ONT.bloom and ONT.pairing_issues files. When I try to open these two files, I couldn't see anything. 
How to increase RAM memory? in my system, 188 GB free RAM is there.

How to solve the problem? 

Thank you.

[con_kei_LINKS.log](https://github.com/bcgsc/LINKS/files/4379956/con_kei_LINKS.log)

**Comment by warrenlr** [comment]
there a mistake in :
```
gunzip -c ONT.fastq.gz | perl -ne '$ct++;if($ct>4){$ct=1;}print if($ct<3);' > ONT.fa
echo ONT.fa_paired.fa > ONT.fof
```
You are generating ONT.fa, but placing "ONT.fa_paired.fa" in ONT.fof
unless I am missing a step..

Anyways, LINKS can read fastq files so all you need is:
echo ONT.fastq.gz > ONT.fof

If RAM is limited, you will have to play with increasing parameter "t"
but that depends on the size of your dataset and genome.

If you are scaffolding a human-size or larger genome with LINKS, I would suggest running one distance interval at a time, and using the output as the input to the next, larger distance run.

**Comment by bioramg** [comment]
Thank you for your valuable suggestion.

The expected mitochondrial genome size is ~1mb. But the ONT nanopore reads contain all genome sequencing reads that include chloroplast, mitochondrial and nuclear genome sequence reads and read size is ~ 8.8 GB. The N50 of nanopore read size 22,193. So, which one is the best t and d option to start with this assembly?
Thank you.
