### ISSUE TITLE
Invalid file of filenames: FULL_PATH -- fatal error

### ISSUE THREAD

**Issue by tarunaaggarwal** [bcgsc/LINKS#50]
Hi @warrenlr - I'm trying to use LINKS to scaffold a pre-assembled genome with Illumina Moleculo reads. I have sam and bam files that I produced using Minimap2 but doesn't look like LINKS needs them. I have a `.fof` file with the absolute PATH of fastq file that contains my Moleculo reads. But I keep getting the following error. 

```
Invalid file of filenames: /home/taruna/hyb1-a2/analysis-results/links/files4link.txt -- fatal
```
I have checked the PATH many times and both the dir and the file are readable. Is there a way I can fix this error? Please advice. Thank you so much!

**Comment by warrenlr** [comment]
How about 
```/home/taruna/hyb1-a2/analysis-results/links/files4link.txt```
itself? 

Does the LINKS demo run ok?  if so, then I'd recommend taking a look at how things are set up for demo runs

hope it helps and thank you for your interest in LINKS!

**Comment by tarunaaggarwal** [comment]
Hey @warrenlr - thanks for responding. I tried that extension before I changed it to `.fof`. I installed LINKS with `conda`. Could that cause any issues? I was having trouble with Github installation instructions. And I just downloaded the `test` directory and ran the `./runme_EcoliK12single.sh` script and it worked just fine. I even tried to put all the files in the same directory and run LINKS but still no luck. I'm getting the same `File does not exist` error.

**Comment by warrenlr** [comment]
did you copy the fastq too?  It might be related to permission issues.  Only thing I can think of

**Comment by lcoombe** [comment]
Hmm very strange... 
@tarunaaggarwal - in case it helps us to figure out what is going on, could you paste your full `LINKS` command, the full standard out + error, and the result of `ls -lah /home/taruna/hyb1-a2/analysis-results/links/files4link.txt` (or whatever file of filenames you are using for the test `LINKS` command you include?

**Comment by tarunaaggarwal** [comment]
Hi @lcoombe - sure thing! I totally agree that it's so strange. Below is everything you asked.

My full command:
`LINKS -f a2_scaffold_1kb.fa -s files4link.txt -b a2-moleculo-scaffolded-asm`

Standard out/error after I run the above command:
```
Running: /home/taruna/miniconda3/bin/LINKS [v1.8.7]
-f a2_scaffold_1kb.fa
-s files4link.txt
-m
-d 4000
-k 15
-e 0.1
-l 5
-a 0.3
-t 2
-o 0
-z 500
-b a2-moleculo-scaffolded-asm
-r
-p 0.001
-x 0

----------------- Verifying files -----------------

Checking /home/taruna/hyb1-a2/analysis-results/links/a2-asm-MAPPEDreads-to-pb2moleculoreads.fastq...ok
Checking ...na
*** File does not exist -- fatal (check the path/file and try again)
```
Output of `ls -lah` of `/home/taruna/hyb1-a2/analysis-results/links`:
```
drwxr-xr-x 2 taruna wilbanks  155 Apr 12 10:55 .
drwxr-xr-x 4 taruna wilbanks   33 Apr 10 14:07 ..
-rw-r--r-- 1 taruna wilbanks  12M Apr 10 14:05 a2-asm-MAPPEDreads-to-pb2moleculoreads.fastq
-rw-r--r-- 1 taruna wilbanks 5.4K Apr 14 09:54 a2-moleculo-scaffolded-asm.log
-rw-r--r-- 1 taruna wilbanks 4.1M Apr 12 10:26 a2_scaffold_1kb.fa
-rw-r--r-- 1 taruna wilbanks   90 Apr 12 10:28 files4link.txt
-rw-r--r-- 1 taruna wilbanks  417 Apr 12 10:55 test.log
```

**Comment by warrenlr** [comment]
I believe that you have an empty line in your fof : "files4link.txt"

**Comment by tarunaaggarwal** [comment]
Oh my god! That stupid empty line was the issue! Ugh! Thank you so much @warrenlr ! I would not have figure that out. I just ran LINKS and it worked! THANKS!
