### ISSUE TITLE
could not make scaffold using long reads

### ISSUE THREAD

**Issue by bioramg** [bcgsc/LINKS#54]
Hi,
I am trying to assemble the plant mitochondrial genomes. I have two contigs such as 430 and 193-kb that contains all mitochondrial genes and I guess repeat regions are present at the end of these two contigs .So, I would like to make scaffold with Nanopore long reads using LINKS with the default parameters as below and attached log file for your reference.
 $LINKS -f ./cke_mt_two_contigs.fasta -s ./cke_ont_ref_gen.fof

I could not obtained any results and moreover the output results showed the exact input contigs only. There is no improvement. How can I make scaffold or what are the parameters that I tweak to get scaffold?

[cke.log](https://github.com/bcgsc/LINKS/files/5613458/cke.log)

Thank you and looking forward to hearing from you.

**Comment by warrenlr** [comment]
Thank you for your message and interest in LINKS.

I'd recommend running LINKS with several distances, in separate runs (-d 15000, -d 10000, -d 7500, -d 5000, -d 2500, -d 1000) or if you have enough memory on your system, all at once (-d 15000,10000,7500,5000,2500,1000).  I recommend that you read the documentation.

Rest of parameters look ok; you could also decrease the pairing requirements (decrease -l and increase -a. eg -l 3 -a 0.5)  

Also, keep in mind that maybe there are no long reads that suitably span the two contigs..

Good luck!

**Comment by bioramg** [comment]
Thank you for your suggestion.
I shall try and let you know if there are issues.
