### ISSUE TITLE
MPET support broken in v2.0.0 ?

### ISSUE THREAD

**Issue by pansapiens** [bcgsc/LINKS#61]
LINKS v2.0.0 seems to be unable to parse the custom colon-separated-interleaved format used for MPET reads.

When running the example `runmeEcoliK12singleMPET.sh` test (from the previous v1.8.7 release), it fails with the error:
```
Read fasta stage
[2021-11-26 12:02:35][ERROR] trimmedmpet4k_1.fa_paired.fa source file is in invalid format!
make: *** [ecoliK12-ONT_linksSingleIterationSCAFF-trimmedMPET.tigpair_checkpoint.tsv] Error 1
```

I also see this with my own MPET data (which is why I resorted to trying the test from a previous release as a sanity check).

As far as I can tell, the MPET reads format is correct according to the docs (with `:` colons in the sequence lines), eg:
```
$ head trimmedmpet4k_1.fa_paired.fa
>M903:194:000000000-A5FBD:1:1101:18208:2411
TGGCAAAAGGACGTTGATTTGCATCAGGTCTTGTGGAGCCGCTCGCGATTAGGTGAACGCCAAAAAGGCCAGGGCATTACACGTGCTGATCATTTC:TTTTCTCTTTTTCCCTCCTTCCTCCTTTCCTTCTCTCCCTTTCTCTTCAACCCTAACACCCACTCTACTGTCTAGCTCTCTCTCTTAGTCAGCCCATGATCACCACCTGTCATTCCCTGCCCTTTTTGGCGTTCCCCTAATCGCGCGCCTC
>M903:194:000000000-A5FBD:1:1101:18825:2432
GGGAGCGCACGGCGTCTTCCGTAGTGGCGATGCCATTCAGGTGATCAT:CGCCTGCCTCCCCTCTTCCTCCGTCCGCCCGTCTTCCCGGCACCCTCACCCTTCCCCCTTTGCCCAGCTGTGTTTACTCGCCCTCTCCTCACCTCAATGGCCTCGCCCCTCCGGCCGCCGCCGTGCCCTCCCACTTCGGAAGCCCGTCCTC
>M903:194:000000000-A5FBD:1:1101:12529:2434
CTCGGTCAGGGCATGGATGTACAAAGCGCGCAGGAGAAGATTGGTCAGGTGGTGGAAGCCTACCGC:TTTCTCCCTTCCCCCCGCCCTTTTTCTCGCTCCTCGCTTTCCCTCTCCCTCTCTCCCTCCCTCCTACCCCGCTCTTCCTCCTGGCATATTCCCTCCCCATCCCGGGAACGGCGCTTACTACCATGACACCGGCCCTGCAACCCCTCCGGTT
>M903:194:000000000-A5FBD:1:1101:16442:2442
GGATATTGATGAAAAAACTCAGTTATAAAGCAGGGATTATTACCGGGTTATTT:CCCTTCATACTGCCGTTCTCCCTGTGGTCGCCTTTACCGGTCAGCGCCATCCACCCGTACACGTCAACCACCACGCGGGTCACGTCTTTAAGCCGGTTACGGG
>M903:194:000000000-A5FBD:1:1101:13831:2502
TGATCGTCCGGGAGCTTTTTACGGCTTAAAATCAGTAAATCGACGTCTGAAAGTGGATGCAGCTCGCCACGACCGTAGCCACCGACGTCGCCCAATTCCAGGTCGGCAATCTGGCTGACTCCCCCTTCACTCCATAAT:CAGCCCTCAGTCCTCCGTTATTCACGGCTTCGCATAAGGACTGTCTCTTCTCCCCATCTCGATGTGTCTAAGCGACCGATTATGGATTGAAGCGGGATTCCGCCAGATTGCCGACCTGGCATTGGTCTCCGTCGGTGGCTCCGGTCGTGCC
```

If I remove the `:` between the two reads such that the file is now 'valid' FASTA (with read 1 and read 2 concatenated on the same line), LINKS accepts this and runs, although I'm not sure if this is correct and would produce sensible results. Skimming the code of it looks as if the accepted MPET format has changed since it's using regular FASTA parsing from `btllib` ? Or is MPET not yet properly supported in v2.0.0 ?

**Comment by MurathanGoktas** [comment]
Hello Andrew, we didn't test v2.0.0 with an MPET dataset. Thanks for flagging this issue. Currently please use v1.8.7 for MPET datasets.

**Comment by pansapiens** [comment]
Thanks for clarifying - will use v1.8.7. Might be worth updating the README.
