### ISSUE TITLE
about running error

### ISSUE THREAD

**Issue by guanttttt** [bcgsc/LINKS#62]
hello！ 
there are some error when i running this method. I have already installed the LINKS by conda, and then i want to use long reads to get scaffols, my command is as follows:
`LINKS -f .../R.sphaeroides/contig/rsph-velvet-nobreaks.fa -s .../R.sphaeroides/linkL/rsph-SRX110617-lr.fasta -b result`
but there was an error :
```
  -f .../R.sphaeroides/contig/rsph-velvet-nobreaks.fa
  -s .../R.sphaeroides/linkL/rsph-SRX110617-lr.txt
  -m 0
  -d 4000
  -k 15
  -j 1
  -t 2
  -o 0
  -e 0.1
  -l 5
  -a 0.3
  -z 500
  -b result
  -r
  -p 0.001
  -x 0
  -v 0
HASHES CALC: 14.377588 second: 9.965784
- Number of bfElements: 4548294
- Input file path:
- Input file: .../R.sphaeroides/contig/rsph-velvet-nobreaks.fa
- kmersize: 15
- m: 65393496
- fpr: 0.001
- hashFct: 9
- Filter output file : 15


Writing Bloom filter to disk () : 1638965878
Done mybf, printing stats...
2258 ms
Read fasta stage
make: *** [..../.conda/envs/links/bin/share/links-2.0.0-0/bin/LINKS-make:131: result.tigpair_checkpoint.tsv] Segment error (core dumped)

```
Was the path of dataset that i used had something wrong? 
In addition, I don't quite understand the format of “fof”, is there any tools to transfer .fasta to .fof ?
Hope you rely, thanks!

**Comment by MurathanGoktas** [comment]
Hello @guanttttt,

You should input file-of-files with -s parameter, not read files directly.

So please try again supplying a file-of-file and let us know if error persists.

Thanks.

Tip:
`echo .../R.sphaeroides/linkL/rsph-SRX110617-lr.fasta >> reads.fof`
