### ISSUE TITLE
How to creating input file : -f "sequences to scaffold" and -s "file-of-filenames"

### ISSUE THREAD

**Issue by Hai1983** [bcgsc/LINKS#63]
Dear everyone.

I try to use LINKS to scaffolding genome assemblies with long reads (PacBio reads -Hifidata).
Now, I have a draft genome with 800 cotigs ~780M and Hifi.fasta file .
It very useful, if possible share me example of these data.

Thanks in advance .

Sincerely.
Hai

**Comment by MurathanGoktas** [comment]
Hello,

If your draft genome name is x.fasta input it as `-f x.fasta`

If you only have one HiFi read dataset, and its name is y.fasta; create a fof file with
`echo y.fasta >> reads.fof`
Then input it as `-s reads.fof`.

Let me know if you have any further questions.
