### ISSUE TITLE
Output is different if the reads are split into two files

### ISSUE THREAD

**Issue by TomHarrop** [bcgsc/LINKS#81]
I'm having an issue where the output from `LINKS` seems to change if the long reads are provided in multiple files. 

I'm testing with a subset of the [long reads](https://www.bcgsc.ca/downloads/supplementary/LINKS/K12_full2dONT_longread.fa) and [pre-computed contigs](https://www.bcgsc.ca/downloads/supplementary/LINKS/ecoliK12_abyss_illumina_contig_baseline.fa) from the README. I'm using three contigs that should get joined into a single scaffold.

If the reads are all in one file, I get the expeced output. If the reads are split across two files, I get three scaffolds (i.e. no scaffolding happens).

I'm using LINKS release v2.0.1. The command I used in each case is

```bash

LINKS \
	-f /path/to/used_contigs.fa.gz \
	-s /path/to/contigs.fof \
	-b links
```

### With reads in a single file:

```bash
$ cat links.assembly_correspondence.tsv 
#This correspondence links.assembly_correspondence.tsv file lists the scaffold ID and contig ID used by LINKS (reported in the .scaffolds file), with the original contig name in the provided assembly file (-f /path/to/used_contigs.fa.gz)
LINKS_scaffold_ID	LINKS_contig_ID	original_name	orientation(f=forward/r=reverse)	number_of_links	links_ratio	gap_or_overlap(-)
scaffold1	1	658 358719 3056919 148-,...,484+	f	26	0	-83
scaffold1	2	669 48119 389147 223-,...,554-	r	11	0	-375
scaffold1	3	688 226353 2008589 541+,567+,217-	r	NA	NA	NA

```

Here's the .fof I used

```
/path/to/reads.fa.gz
```

### With the same reads split into two files:

```bash
$ cat links.assembly_correspondence.tsv 
#This correspondence links.assembly_correspondence.tsv file lists the scaffold ID and contig ID used by LINKS (reported in the .scaffolds file), with the original contig name in the provided assembly file (-f /path/to/used_contigs.fa.gz)
LINKS_scaffold_ID	LINKS_contig_ID	original_name	orientation(f=forward/r=reverse)	number_of_links	links_ratio	gap_or_overlap(-)
scaffold1	1	658 358719 3056919 148-,...,484+	f	NA	NA	NA
scaffold2	3	688 226353 2008589 541+,567+,217-	f	NA	NA	NA
scaffold3	2	669 48119 389147 223-,...,554-	f	NA	NA	NA
```

Here's the .fof I used

```
/path/to/chunk_0.fa.gz
/path/to/chunk_1.fa.gz
```

### Checking if the reads are the same:

```bash
$ zcat reads.fa.gz | sha256sum
12853ab45257979ae8f96b75cd673a1e84bb0a0c64e872cb56b6a2df042db34a  -
```

```bash
$ zcat chunk_0.fa.gz chunk_1.fa.gz | sha256sum
12853ab45257979ae8f96b75cd673a1e84bb0a0c64e872cb56b6a2df042db34a  -
```

### The files:

- [Contigs](https://github.com/bcgsc/LINKS/files/8020876/used_contigs.fa.gz)
- [All reads](https://github.com/bcgsc/LINKS/files/8020878/reads.fa.gz)
- Chunks
  - [chunk_0](https://github.com/bcgsc/LINKS/files/8020883/chunk_0.fa.gz)
  - [chunk_1](https://github.com/bcgsc/LINKS/files/8020884/chunk_1.fa.gz)

**Comment by MurathanGoktas** [comment]
Hello, @TomHarrop thank you for your very clear explanation and for pointing out the bug. I believe I fixed the bug with the latest commit to master branch. For now please manually install LINKS from the source code if you depend on that feature.

Please let us know if you observe another bug and thanks for your interest in using LINKS. 

Best

**Comment by TomHarrop** [comment]
Hi @MurathanGoktas 

Thanks for the quick fix. I've tested at commit ab54b4a and now I get the expected output.

I'm developing a Galaxy wrapper for LINKS, so I'll be able to include the fix when there's a new release of LINKS.

Thanks again,
Tom
