### ISSUE TITLE
Pipeline stuck after "Reading sequence reads"

### ISSUE THREAD

**Issue by jzohren** [bcgsc/LINKS#82]
I have tried running the pipeline a couple of times with various parameter settings (changing -t, -d, and -k), but it always gets stuck after `STAGE: Reading sequence reads`. The demo worked fine, so the installation should not be the problem. I also don't think this is due to memory as I've tried with just a handful (110,047) of PacBio reads and the genome I want to scaffold is only 76 MB. One of the jobs was running for several days, but still didn't progress past the reading sequence reads stage. I'm using v2.0.1 via a conda installation.

Here's the log output:

```
Running Command: LINKS-make LINKS draft=/camp/lab/turnerj/working/jasmin/data/Dovetail/data/chrX-reordering/new_order_v5.fasta readsFof=reads.fof    j=32
LINKS_CPP -f /camp/lab/turnerj/working/jasmin/data/Dovetail/data/chrX-reordering/new_order_v5.fasta -s reads.fof   -d 4000 -k 15 -t 2 -j 32 -l 5 -o 0 -e 0.1 -z 500 -p 0.001 -b k15_t2_l5_a0.3_o0_e0.1 -v 0 -x 0

LINKS running options:
  -f /camp/lab/turnerj/working/jasmin/data/Dovetail/data/chrX-reordering/new_order_v5.fasta
  -s reads.fof
  -d 4000
  -k 15
  -j 32
  -t 2
  -o 0
  -e 0.1
  -l 5
  -a 0.3
  -z 500
  -b k15_t2_l5_a0.3_o0_e0.1
  -r
  -p 0.001
  -x 0
  -v 0

STAGE: Bloom filter construction/read
- Number of BF Elements: 78858444
- Input file path: k15_t2_l5_a0.3_o0_e0.1
- Input file: /camp/lab/turnerj/working/jasmin/data/Dovetail/data/chrX-reordering/new_order_v5.fasta
- kmersize: 15
- m: 1133794184
- fpr: 0.001
- hashFct: 9
- Filter output file : 15


Writing Bloom filter to disk (k15_t2_l5_a0.3_o0_e0.1.bloom)
Bloom filter generated or loaded in: 0h 0m 43s 749ms

STAGE: Reading sequence reads
Reading: /camp/lab/turnerj/working/jasmin/data/Dovetail/PB/m64044_all_pacbio_reads_0.01.fastq
Processed read count: 100000 - 110047
```

Any help or pointers would be much appreciated! 

Thanks,
Jasmin

**Comment by MurathanGoktas** [comment]
Hello @jzohren ,

This is a strange error. My first guess is that its due to thread number in your command. LINKS currently cannot scale up to 32 threads, probably in your run some threads couldn't initiate and couldn't join to main thread. Please try at most `-j 3` and let me know if the issue persists or not.

**Comment by jzohren** [comment]
Hi @MurathanGoktas,

Thanks for your swift reply! I set `-j 3` and it worked fine, so it seems that that was the issue. I just thought I'd throw many threads at it to speed it up, but clearly I was wrong. I'll start another run with my complete data set now, hopefully this'll work equally well. 

Cheers,
Jasmin

**Comment by MurathanGoktas** [comment]
Hello @jzohren ,

I am happy that it worked out. It is a bug, thanks for reporting it and good luck with your projects.
