### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 123chenshixin** [bcgsc/LINKS#83]
I am using LINKS to scaffold my assemble by using nanopore data. My command is:
`LINKS -f ./contig.fa -j 56 -s ./file.fof -b scaffold`
The content of file.fof is:

> ../ONT_clean_data/Ach_clean.fastq.gz
The stdout is:

> Running Command: LINKS-make LINKS draft=./contig.fa readsFof=./file.fof    j=56      b=scaffold
LINKS_CPP -f ./contig.fa -s ./file.fof   -d 4000 -k 15 -t 2 -j 56 -l 5 -o 0 -e 0.1 -z 500 -p 0.001 -b scaffold -v 0 -x 0

LINKS running options:
  -f ./contig.fa
  -s ./file.fof
  -d 4000
  -k 15
  -j 56
  -t 2
  -o 0
  -e 0.1
  -l 5
  -a 0.3
  -z 500
  -b scaffold
  -r
  -p 0.001
  -x 0
  -v 0

STAGE: Bloom filter construction/read
- Number of BF Elements: 335299079
- Input file path: scaffold
- Input file: ./contig.fa
- kmersize: 15
- m: 4820791840
- fpr: 0.001
- hashFct: 9
- Filter output file : 15

Writing Bloom filter to disk (scaffold.bloom)
Bloom filter generated or loaded in: 0h 1m 57s 478ms

STAGE: Reading sequence reads
Reading: ../ONT_clean_data/Ach_clean.fastq.gz
Processed read count: 100000 - 200000 - 300000 - 400000 - 500000 - 600000 - 700000 - 800000 - 900000 - 1000000 - 1100000 - 1200000 - 1300000 - 1400000 - 1500000
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
make: *** [/home/cxs3_z4/software/miniconda3/bin/LINKS-make-real:122: scaffold.tigpair_checkpoint.tsv] Aborted

I don't know what hanppen. I install LINKS by conda. Is it any problem? Hopefully, you could give me valuable advice.

**Comment by MurathanGoktas** [comment]
Hello,

Please run LINKS with 3 threads at most, `-j 3`. Problem was previously mentioned at [issue #82](https://github.com/bcgsc/LINKS/issues/82).

Good luck with your work.
